### ISSUE TITLE
Malformed header cause failure

### ISSUE THREAD

**Issue by yoavst** [kittinunf/Fuel#102]
HTTP normal headers:

```
header1: value1 \r\n
header2: value2 \r\n
```

So, if we set a malformed value, for example `a\nb\nc`:

``` kotlin
Fuel.get("https://www.google.com/").header("sample" to "a\nb\nc").responseString { request, response, result -> 
 result.failure {
   it.printStackTrace()
}
}
```

we get:

```
Exception : Illegal character(s) in message header value: a
b
c
    at com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:69)
    at com.github.kittinunf.fuel.core.requests.TaskRequest.call(TaskRequest.kt:17)
    at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:13)
    at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:6)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.github.kittinunf.fuel.core.FuelManager$executor$2$1$1.run(FuelManager.kt:43)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ParkerK** [comment]
Is this a bug? What should be the outcome of this, if the user supplies a malformed header?

**Comment by JairAviles** [comment]
Is that being said, which is the correct way to set wellformed headers for a GET request?

**Comment by markGilchrist** [comment]
@yoavst , I have raised a small pr with this issue as a unit test. I feel that the current behaviour is correct. If you want to to be handled differently please specify how and I will address this in my current pr. if not I would suggest we close? @kittinunf
