### ISSUE TITLE
How can I send requests to secure HTTP server?

### ISSUE THREAD

**Issue by dphans** [kittinunf/Fuel#262]
I got error while requesting to my server (that using secure https):

> javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                    at com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:63)
                                                                    at com.github.kittinunf.fuel.core.requests.TaskRequest.call(TaskRequest.kt:14)
                                                                    at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:11)
                                                                    at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:6)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                    at com.github.kittinunf.fuel.core.FuelManager$executor$2$1$1.run(FuelManager.kt:48)
                                                                    at java.lang.Thread.run(Thread.java:764)
                                                                 Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                    at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:219)
                                                                    at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
                                                                    at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
                                                                    at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
                                                                    at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
                                                                    at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                                                                    at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                                                                    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
                                                                    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
                                                                    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
                                                                    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
                                                                    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
                                                                    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
                                                                    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
                                                                    at com.github.kittinunf.fuel.toolbox.HttpClient.setBodyIfDoOutput(HttpClient.kt:92)
                                                                    at com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:40)
                                                                    at com.github.kittinunf.fuel.core.requests.TaskRequest.call(TaskRequest.kt:14) 
                                                                    at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:11) 
                                                                    at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:6) 
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                    at com.github.kittinunf.fuel.core.FuelManager$executor$2$1$1.run(FuelManager.kt:48) 
                                                                    at java.lang.Thread.run(Thread.java:764) 

How can I import keystore into Fuel or use something like okhttp?

**Comment by jameslan** [comment]
Have you tried `FuelManager.instance.keystore`?

**Comment by kittinunf** [comment]
I think this should work. I will close this for now, feel free to re-open if you disagree.
