### ISSUE TITLE
Got IndexOutOfBoundException when upload file

### ISSUE THREAD

**Issue by babedev** [kittinunf/Fuel#298]
Fuel: `v1.12.0`

I got IndexOutOfBoundException when upload file which selected from Android gallery

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.get(ArrayList.java:437)
at com.github.kittinunf.fuel.core.requests.UploadTaskRequest.<init>(UploadTaskRequest.kt:63)
at com.github.kittinunf.fuel.core.Request$taskRequest$2.invoke(Request.kt:63)
at com.github.kittinunf.fuel.core.Request$taskRequest$2.invoke(Request.kt:23)
```

Here is my code

```kotlin
"files".httpUpload()
    .source { _, _ ->
        file // File from Android gallery
    }
    .name { file.name }
    .timeout(30000)
    .responseString { _, _, _ -> }
```

I checked that it cannot get boundary from `Content-Type`

```kotlin
private val boundary = request.headers["Content-Type"]?.split("=", limit = 2)?.get(1) ?: System.currentTimeMillis().toString(16)
```

**Comment by kittinunf** [comment]
Thanks for reporting this :)
