### ISSUE TITLE
Uncatchable java.net.ConnectException

### ISSUE THREAD

**Issue by dazwin** [kittinunf/Fuel#304]
If the server is not running when request is made, Fuel re-throws this exception and the application quits. With the lambda, it's not possible to catch this exception:

Example code:
```
        Fuel.get("http://localhost").responseJson { request, response, result ->
        }
```

Here's an example stack trace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: ####, PID: 6369
                  java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:448)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
                   Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:5001
                      at com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:63)
                      at com.github.kittinunf.fuel.core.requests.TaskRequest.call(TaskRequest.kt:14)
                      at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:11)
                      at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:6)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                      at com.github.kittinunf.fuel.core.FuelManager$executor$2$1$1.run(FuelManager.kt:48)
                      at java.lang.Thread.run(Thread.java:764)
                   Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:5001
                      at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
                      at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
                      at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
                      at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                      at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
                      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:163)
                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:207)
                      at java.net.URLConnection.getContentEncoding(URLConnection.java:520)
                      at com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:43)
                      at com.github.kittinunf.fuel.core.requests.TaskRequest.call(TaskRequest.kt:14) 
                      at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:11) 
                      at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:6) 
                      at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                      at com.github.kittinunf.fuel.core.FuelManager$executor$2$1$1.run(FuelManager.kt:48) 
                      at java.lang.Thread.run(Thread.java:764) 
```

The problem lies here (TaskRequest.kt, around line 18):
```
    } catch (error: FuelError) {
        if (error.exception as? InterruptedIOException != null) {
            interruptCallback?.invoke(request)
        }
        throw error
    }
```

**Comment by markGilchrist** [comment]
@dazwin  @vcartera81  I have an open pr to fix this https://github.com/kittinunf/Fuel/pull/382
