### ISSUE TITLE
Avoiding resource leaks - Explicit termination method 'end' not called

### ISSUE THREAD

**Issue by MaTriXy** [kittinunf/Fuel#315]
Using Fuel with get can cause resource leaks. 

Turn on Strict mode and watch the error: 

> A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                 java.lang.Throwable: Explicit termination method 'end' not called
                                     at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                     at java.util.zip.Inflater.<init>(Inflater.java:104)
                                     at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:76)
                                     at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:89)
                                     at com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:53)
                                     at com.github.kittinunf.fuel.core.requests.TaskRequest.call(TaskRequest.kt:14)
                                     at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:80)
                                     at com.github.kittinunf.fuel.core.Request.responseString(Request.kt:284)
                                     at com.github.kittinunf.fuel.core.Request.responseString$default(Request.kt:284)
                                     at com.github.kittinunf.fuel.core.Request.responseString(Request.kt)

**Comment by markGilchrist** [comment]
in the source code

```
// As per Android documentation, a connection that is not explicitly disconnected
// will be pooled and reused!  So, don't close it as we need inputStream later!
// connection.disconnect()
```

**Comment by imknown** [comment]
Just ignore this when releasing apk withou StrictMode?
