### ISSUE TITLE
What will happen if deserializing will throw an error?

### ISSUE THREAD

**Issue by kenrube** [kittinunf/Fuel#356]
@kittinunf I have a question. I look at source code of _Deserializable_ class and see this:
```kotlin
fun <T : Any, U : Deserializable<T>> Request.response(deserializable: U): Triple<Request, Response, Result<T, FuelError>> = try {
    val response = taskRequest.call()
    Triple(this, response, Result.Success(deserializable.deserialize(response)))
} catch (error: FuelError) {
    Triple(this, error.response, Result.error(error))
}
```
I understand why you catch **FuelError** (_taskRequest.call()_ throw it in case of error) but what'll happen if error in _deserializable.deserialize(response))_ (let's say json parsing error)? As far as I understand this exception won't wrapped into **FuelError** so result type won't be **Result.Error**, am I right? How to properly handle this case?

**Comment by markGilchrist** [comment]
my experience of this is the deserialisation error is caught and returned in the catch block

**Comment by kenrube** [comment]
In my case deserialization error crashes entire app with similar stacktrace:
```
java.lang.IllegalStateException: Not a JSON Object: null
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
        at my.fuel.app.SomeResponse$Deserializer.deserialize(SomeResponse.kt:15)
        at my.fuel.app.SomeResponse$Deserializer.deserialize(SomeResponse.kt:13)
        at com.github.kittinunf.fuel.core.ResponseDeserializable$DefaultImpls.deserialize(Deserializable.kt:18)
        at my.fuel.app.SomeResponse$Deserializer.deserialize(SomeResponse.kt:13)
        at my.fuel.app.SomeResponse$Deserializer.deserialize(SomeResponse.kt:13)
        at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:81)
        at com.github.kittinunf.fuel.rx.RxFuelKt$rx_result$1.subscribe(RxFuel.kt:31)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
        at io.reactivex.Single.subscribe(Single.java:3220)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3220)
        at io.reactivex.internal.operators.single.SingleZipArray.subscribeActual(SingleZipArray.java:64)
        at io.reactivex.Single.subscribe(Single.java:3220)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3220)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```
And code:
```kotlin
manageDisposable(
    RestProvider.getSomeResponse()
        .map { it.get() }
        .subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(
            {
                sendToView { it.hideProgress() }
                sendToView { it.showData(it.data) }
            },
            { throwable ->
                sendToView { it.hideProgress() }
                sendToView { it.showErrorMessage(throwable.localizedMessage) }
                Timber.e(throwable.localizedMessage)
            }
        )
)
```
```kotlin
override fun getSomeResponse() =
    "https://www.some.site/some/url"
        .httpGet()
        .rx_object(SomeResponse.Deserializer())
```
```kotlin
data class SomeResponse(
    val data: Any
) {
    class Deserializer : ResponseDeserializable<SomeResponse> {
        override fun deserialize(content: String): SomeResponse {
            val jsonObject = JsonParser().parse(content).asJsonObject
            val data = ...
            return SomeResponse(data)
        }
    }
}
```

**Comment by markGilchrist** [comment]
Can we close this issue as the above pr is merged in ?

**Comment by kenrube** [comment]
Yes of course! Thanks for this PR, @markGilchrist ! Now waiting for release :)

**Comment by markGilchrist** [comment]
@kenrube  I believe that the release may be happening soon! many thanks for taking the time to raise an issue and please let us know if we can improve things in the future
