### ISSUE TITLE
Jackson response deserialization doesn't work with response interceptor

### ISSUE THREAD

**Issue by msogrin** [kittinunf/Fuel#364]
If `loggingResponseInterceptor()` is used, then JSON response deserialization by fuel-jackson fails due to response stream being already consumed/read. 

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4133)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3065)
	at <removed>$$inlined$responseObject$1.deserialize(FuelJackson.kt:51)
	at com.github.kittinunf.fuel.core.ResponseDeserializable$DefaultImpls.deserialize(Deserializable.kt:15)
	at <removed>$$inlined$responseObject$1.deserialize(FuelJackson.kt:28)
	at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:81)
```

**Comment by lucasvalenteds** [comment]
@msogrin Could share the version of Fuel that this is happening, please? A test case or code sample that reproduces the exception may be useful too. The test below should reproduces what I understood of your report, but it's passing with code from commit e7095ee.

```kotlin
private data class Ip(val origin: String)

private object IpDeserializer : ResponseDeserializable<Ip> {
    override fun deserialize(content: String) = 
            jacksonObjectMapper().readValue<Ip>(content)
}

@Test
fun jacksonCanDeserializeWhileUsingResponseInterceptor() {
    val manager = FuelManager.instance.apply {
        addResponseInterceptor { loggingResponseInterceptor() }
    }

    val (_, _, result) = manager.request(Method.GET, "https://httpbin.org/ip")
            .responseObject(IpDeserializer)

    result.fold({ data ->
        assertTrue(data.origin.isNotEmpty())
    }, { error ->
        fail("This test should pass but got an error: ${error.message}")
    })
}
```

**Comment by msogrin** [comment]
@lucasvalenteds you don't actually use the code from `fuel-jackson` module, so your `IpDeserializer` is one of the possible work-arounds that makes it work (by forcing deserialization from String).

Use of provided `jacksonDeserializerOf` object from https://github.com/kittinunf/Fuel/blob/master/fuel-jackson/src/main/kotlin/com/github/kittinunf/fuel/jackson/FuelJackson.kt#L28 (if you call it via one of methods in https://github.com/kittinunf/Fuel/blob/master/fuel-jackson/src/main/kotlin/com/github/kittinunf/fuel/jackson/FuelJackson.kt#L20-L26) makes it go via `Reader` implementation, where the reader/stream is already consumed by the interceptor and pointing to EOF.

I had previously reproduced the problem with Fuel 1.12.1 and 1.13.0.

**Comment by lucasvalenteds** [comment]
Thank you for the clarification, @msogrin. I understood it now. I'll try to work on this soon, but feel free to send a PR if you have a solution. :+1:

**Comment by markGilchrist** [comment]
@msogrin can you share the code you are using so I can write a test?

**Comment by markGilchrist** [comment]
will this pr solve this? https://github.com/kittinunf/Fuel/pull/402

**Comment by kittinunf** [comment]
I don't think so, I will take on it for the next release.

**Comment by SleeplessByte** [comment]
@msogrin sorry this took so long. It has been fixed, with a test to prove it is.
