### ISSUE TITLE
 Caused by: com.github.kittinunf.fuel.core.HttpException: HTTP Exception 404 Not Found

### ISSUE THREAD

**Issue by congfandi** [kittinunf/Fuel#366]
i got error in httppost.. plase help
```java
 @SuppressLint("ShowToast")
    private fun getData(npa: String) {
        progressbar.visibility = View.VISIBLE
        val json = JSONObject()
        json.put("npa", npa)
        try {
            NPA.httpPost(listOf("npa" to npa))
                    .header()
                    .timeout(5000)
                    .timeoutRead(60000)
                    .responseString { _, response, result ->
                        progressbar.visibility = View.GONE
                        when (result) {
                            is Result.Failure -> {
                                Log.d("hasil gagal", result.get())
                            }
                            is Result.Success -> {
                                try {
                                    Log.d("hasil sukses", result.get())
                                }catch (e: HttpException) {
                                    Log.d("hasil gagal", result.get())
                                }
                            }

                        }
                    }
        } catch (e: HttpException) {
        }
    }

```
this the error
```console
06-14 19:14:37.041 17102-17102/com.gentasoft.pdgikabpasuruan E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gentasoft.pdgikabpasuruan, PID: 17102
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) 
     Caused by: com.github.kittinunf.fuel.core.HttpException: HTTP Exception 404 Not Found
        at com.github.kittinunf.fuel.core.interceptors.ValidatorInterceptorKt$validatorResponseInterceptor$1$1.invoke(ValidatorInterceptor.kt:12)
        at com.github.kittinunf.fuel.core.interceptors.ValidatorInterceptorKt$validatorResponseInterceptor$1$1.invoke(ValidatorInterceptor.kt)
        at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt:35)
        at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt)
        at com.github.kittinunf.fuel.core.requests.TaskRequest.call(TaskRequest.kt:16)
        at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:11)
        at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:6)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: com.github.kittinunf.fuel.core.HttpException: HTTP Exception 404 Not Found
        at com.github.kittinunf.fuel.core.interceptors.ValidatorInterceptorKt$validatorResponseInterceptor$1$1.invoke(ValidatorInterceptor.kt:12) 
        at com.github.kittinunf.fuel.core.interceptors.ValidatorInterceptorKt$validatorResponseInterceptor$1$1.invoke(ValidatorInterceptor.kt) 
        at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt:35) 
        at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt) 
        at com.github.kittinunf.fuel.core.requests.TaskRequest.call(TaskRequest.kt:16) 
        at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:11) 
        at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:6) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:760) 
```

**Comment by markGilchrist** [comment]
try changing 
```
} catch (e: HttpException) { }
```

to
```
} catch (e: FuelError) { }
```

**Comment by markGilchrist** [comment]
@congfandi  did the above solve your problem, can we close this issue?

**Comment by congfandi** [comment]
@markGilchrist  ty i'll try tomorrow sir

**Comment by congfandi** [comment]
its working but i cant get messagebody from API when return code is higher then 200.  please fix this

**Comment by congfandi** [comment]
i already do that, but i receive error message from , not body message from API.

**Comment by markGilchrist** [comment]
if there is an error then there may not be a body?
instead of doing result.get() why don't you use the response object? which you can access inside the scope of the lambda?

**Comment by markGilchrist** [comment]
@congfandi  is this resolved? can we close this?
