### ISSUE TITLE
High memory consumption when downloading large files with Fuel 1.15.0

### ISSUE THREAD

**Issue by mmuth** [kittinunf/Fuel#414]
Hi there!

We recently updated from Fuel 1.14.0 to 1.15.0. Now we noticed that the memory footprint of the download became dramatically worse and the client throws an OOM error. The code I wrote ist basically just a blocking download like this:

```
fun main(args: Array<String>) {
    val (_, result, _) = Fuel.download("http://my-server.com/api/v1/download").destination { response, url ->
            File("${BASE_PATH}/${TARGET_FILE}")
        }.progress { readBytes, totalBytes ->            
            printImportProgress(readBytes)
        }.response()

        if (result.statusCode == 200) {
            println("Download completed")
        } else {
            // handle error...
        }
} 
```
The file I am trying to download has about 1.5GB of size. With an Xmx of 500M, the old Fuel 1.14 took about 50-100MB of RAM and downloaded everything fine. With Fuel 1.15 the OOM Exception is thrown after downloading not even 150MB of the file.

The stacktrace is
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at com.github.kittinunf.fuel.util.InputStreamsKt.copyTo(InputStreams.kt:14)
	at com.github.kittinunf.fuel.core.requests.DownloadTaskRequest.call(DownloadTaskRequest.kt:19)
	at com.github.kittinunf.fuel.core.DeserializableKt$response$result$1.invoke(Deserializable.kt:81)
	at com.github.kittinunf.fuel.core.DeserializableKt$response$result$1.invoke(Deserializable.kt)
	at com.github.kittinunf.result.Result$Companion.of(Result.kt:116)
	at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:81)
	at com.github.kittinunf.fuel.core.Request.response(Request.kt:321)
	at com.meisterplan.onpremise.control.commands.OnlineUpdateKt.main(OnlineUpdate.kt:146)

```
Thanks and Regards
Matthias

PS: I probably will take a look into the code and trying to fix it. However posting this here in case I don't find time soon...

**Comment by markGilchrist** [comment]
@mmuth  how are you getting on  with fixing this? do you need a hand?

**Comment by markGilchrist** [comment]
@mmuth 

do you still have high memory consumption if you do

``` kotlin
 Fuel.download("http://my-server.com/api/v1/download").destination { response, url ->
            File("${BASE_PATH}/${TARGET_FILE}")
        }.progress { readBytes, totalBytes ->            
            printImportProgress(readBytes)
        }.response{ _,result,_
        if (result.statusCode == 200) {
            println("Download completed")
        } else {
            // handle error...
        }
}

```

?

**Comment by charshep** [comment]
My latest comment in issue #108 may be related?

**Comment by stephenbyrne-mfj** [comment]
The problem is in `com.github.kittinunf.fuel.util.InputStream.copyTo`. While reading the stream and writing it to the file, it also writes it to a `ByteArrayOutputStream` so it can send it to the `onComplete` listener.

**Comment by stephenbyrne-mfj** [comment]
I have started a few attempts to address this, which I will describe and point out my concerns:

#### 1.  `Response.data` is blank for downloads.
Currently, when calling `Fuel.download()` you must provide a file via `Request.destination()`.

After the response is written to the supplied file, set `Response.data` to an empty `ByteArray`. Document that the data will be empty at `Fuel.download()`, `Requestion.destination()`, and `Response.data`. The caller must read from the file.

Pros:
- Easy implementation that touches very little code.

Cons:
- Will break existing code.
- Does break unit tests.
- Worse API.

#### 2. `Response` is overridden to load `data` and `dataStream` from the file
Make `Response` and `Response.data` open. `DownloadTaskRequest` returns a type that extends `Request` that overrides `dataStream` and `data` to lazily load from the file that the data was saved to.

Add `Request.responseInputStream()` which creates a `Result` with an `InputStream` that reads from the file (because of the overridden `Response.dataStream`). The caller must take care to close the `InputStream`.

Add `Request.responseUnit()` which creates a `Result` with `Unit`. After calling this method, the caller must get the data from the file.

Pros:
- Does not break existing code.
- Gives the caller the option of getting a `ByteArray`, an `InputStream`, or reading directly from the file.

Cons:
- Have to make `Result` open.

#### 3. Get rid of `Response.data`.

Get rid of `Response.data` and `Request.destination()`. Make the deserializers read from `Response.dataStream` and do something appropriate. Create a deserializer that writes to a file (e.g.: by adding to Request: `fun responseSave( file:File )` that creates a deserializer that writes to a file).

Pros:
- Caller gets control of what is done with the data.
- Makes it clear to the caller when the data will be loaded into memory.
- Caller indicates how response is handled at response handling (via `reponseSave()`) instead of earlier (via `destination()`).

Cons:
- Major API change
