### ISSUE TITLE
NoClassDefFoundError in local test of android project

### ISSUE THREAD

**Issue by Listade** [kittinunf/Fuel#504]
java.lang.NoClassDefFoundError: kotlin/coroutines/Continuation

	at com.sintez.hardware.FiscalRpcFuelTest.createOrder(FiscalRpcFuelTest.kt:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
    Caused by: java.lang.ClassNotFoundException: kotlin.coroutines.Continuation
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(":aidldefinitions")
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'

    androidTestImplementation 'com.android.support.test:rules:1.0.2'

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation 'com.github.MarcinMoskala.ActivityStarter:activitystarter:1.10-beta'
    implementation 'com.github.MarcinMoskala.ActivityStarter:activitystarter-kotlin:1.10-beta'
    kapt 'com.github.MarcinMoskala.ActivityStarter:activitystarter-compiler:1.10-beta'

    testImplementation 'com.github.kittinunf.fuel:fuel:1.16.0'
    testImplementation 'com.github.kittinunf.fuel:fuel-gson:1.16.0'

    implementation 'com.github.briandilley.jsonrpc4j:jsonrpc4j:1.5.3'
}


```

**Comment by SleeplessByte** [comment]
It seems you're not actually loading `coroutines` in your dependencies (neither `fuel-coroutines`, nor `kotlinx-coroutines`). 

The android sample uses them --- maybe you do to?

**Comment by iNoles** [comment]
As for Android, it requires two kinds of coroutines.
1) Fuel-corountines (core)
2) kotlinx-coroutines-android (Android's UI only)

**Comment by Listade** [comment]
Thanks, guys

**Comment by SleeplessByte** [comment]
I think that means you got it working. I'm closing this, but reply here if you need more help!
