### ISSUE TITLE
The sample app is crashing in current master

### ISSUE THREAD

**Issue by worker8** [kittinunf/Fuel#522]
# Bug Report
The sample app is crashing in current master

## Description

This is the crash log:
```
--------- beginning of crash
2018-11-10 14:38:59.652 30783-30783/com.example.fuel E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.fuel, PID: 30783
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: java.lang.IllegalStateException: The input has already been written to an output stream and can not be consumed again.
        at com.github.kittinunf.fuel.core.DefaultBody$Companion$CONSUMED_STREAM$1.invoke(Body.kt:122)
        at com.github.kittinunf.fuel.core.DefaultBody$Companion$CONSUMED_STREAM$1.invoke(Body.kt:116)
        at com.github.kittinunf.fuel.core.DefaultBody.writeTo(Body.kt:94)
        at com.github.kittinunf.fuel.core.DefaultBody.toByteArray(Body.kt:78)
        at com.github.kittinunf.fuel.core.Request.cUrlString(Request.kt:509)
        at com.example.fuel.MainActivity$httpPut$1.invoke(MainActivity.kt:149)
        at com.example.fuel.MainActivity$httpPut$1.invoke(MainActivity.kt:33)
        at com.github.kittinunf.fuel.core.DeserializableKt$response$1.invoke(Deserializable.kt:49)
        at com.github.kittinunf.fuel.core.DeserializableKt$response$1.invoke(Unknown Source:4)
        at com.github.kittinunf.fuel.core.DeserializableKt$response$5$1.invoke(Deserializable.kt:76)
        at com.github.kittinunf.fuel.core.DeserializableKt$response$5$1.invoke(Unknown Source:0)
        at com.github.kittinunf.fuel.core.Request$callback$1.run(Request.kt:435)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: java.lang.IllegalStateException: The input has already been written to an output stream and can not be consumed again.
        at com.github.kittinunf.fuel.core.DefaultBody$Companion$CONSUMED_STREAM$1.invoke(Body.kt:122) 
        at com.github.kittinunf.fuel.core.DefaultBody$Companion$CONSUMED_STREAM$1.invoke(Body.kt:116) 
        at com.github.kittinunf.fuel.core.DefaultBody.writeTo(Body.kt:94) 
        at com.github.kittinunf.fuel.core.DefaultBody.toByteArray(Body.kt:78) 
        at com.github.kittinunf.fuel.core.Request.cUrlString(Request.kt:509) 
        at com.example.fuel.MainActivity$httpPut$1.invoke(MainActivity.kt:149) 
        at com.example.fuel.MainActivity$httpPut$1.invoke(MainActivity.kt:33) 
        at com.github.kittinunf.fuel.core.DeserializableKt$response$1.invoke(Deserializable.kt:49) 
        at com.github.kittinunf.fuel.core.DeserializableKt$response$1.invoke(Unknown Source:4) 
        at com.github.kittinunf.fuel.core.DeserializableKt$response$5$1.invoke(Deserializable.kt:76) 
        at com.github.kittinunf.fuel.core.DeserializableKt$response$5$1.invoke(Unknown Source:0) 
        at com.github.kittinunf.fuel.core.Request$callback$1.run(Request.kt:435) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

## To Reproduce
1. Grab the sample from current master (2ae065cfea3c0b38ac1256c20894eaf6bb7d6956), compile and launch the app.
2. Launch this activity (https://github.com/kittinunf/Fuel/blob/master/sample/src/main/kotlin/com/example/fuel/MainActivity.kt)
3. Click on the `GO` button
4. Enjoy the crash 💣 
Fun fact: `GO COROUTIUNES` button doesn't crash, and works fine though

## Expected behavior
Should not crash

<details>
<summary>
</summary>
## Screenshots
N/A

## Environment
N/A

### Development Machine
N/A

### Smartphone or Emulator
N/A

## Additional context
N/A

</details>

**Comment by SleeplessByte** [comment]
@worker8 Fixed! :dancer:
