### ISSUE TITLE
SSL or Connection Issue causing crashes

### ISSUE THREAD

**Issue by ChrissinjinTurner** [kittinunf/fuel#659]
# Bug Report

## Description
I want to start out by saying sorry if this was already answered elsewhere, I tried looking but didn't seem to find anything. Over the past couple weeks my android app has been having multiple crashes. On average 3-4 a day that get reported. They are all kind of similar but different enough to create different issues. They seem to be related to either the connection to our API or SSL. To give some context, I picked up the app after it had gone without updates for about a year. So while updating it and adding new features I also updated the third party libraries that were being used. I upgraded the Fuel version from 1.15 - 2.1.0. Since that recent upgrade the crashes have been occurring consistently. Any help would be greatly appreciated. 

## To Reproduce
I have been unable to reproduce the crashes in a test environment. It seems to only happen in the production environment. I have attempted to reproduce by forcing a timeout using `https://httpbin.org/delay/5` but that didn't cause the error to occur. 

## Expected behavior
Prior to the upgrade there were no crashes related to Fuel. 

### Development Machine
 - OS: macOS Mojave
 - IDE: Android Studio
 - Fuel version: 2.1.0
 - Kotlin version: 1.3

### Smartphone or Emulator
The crash seems to be occurring on newer devices. I'm seeing a lot of Galaxy S7 - S8 and Note 7 - 8's as well as various Pixels. All running newer versions of android (8.0 - 9.0). 

## Additional context
Here is one of the stack traces from one of the crashes. I chose this one because it has the most reported crashes, the others are slightly different but I feel are caused by the same problem. I can attach others if needed. 

```java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
  Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Method.java:-2)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
    Caused by: com.github.kittinunf.fuel.core.BubbleFuelError: timeout
      at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:84)
      at com.github.kittinunf.fuel.core.FuelError$Companion.wrap$default(FuelError.kt:83)
      at com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:30)
      at com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:20)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
      at java.lang.Thread.run(Thread.java:764)
      Caused by: com.github.kittinunf.fuel.core.FuelError: timeout
        at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
        at com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:40)
        Caused by: java.net.SocketTimeoutException: timeout
          at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:221)
          at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
          at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
          at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
          at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
          at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
          at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:395)
          at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:144)
          at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:887)
          at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:759)
          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:480)
          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:416)
          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:163)
          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:223)
          at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderFields(DelegatingHttpsURLConnection.java:178)
          at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderFields(HttpsURLConnectionImpl.java:26)
          at com.github.kittinunf.fuel.toolbox.HttpClient.retrieveResponse(HttpClient.kt:131)
          at com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:75)
          at com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:38)
          at com.github.kittinunf.fuel.core.requests.RequestTask.executeRequest(RequestTask.kt:23)
          at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:44)
          at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
          at com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:28)
          at com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:20)
          at java.util.concurrent.FutureTask.run(FutureTask.java:266)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
          at java.lang.Thread.run(Thread.java:764)
          Caused by: java.net.SocketException: socket is closed
            at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:584)
            at com.android.okhttp.okio.Okio$2.read(Okio.java:141)
            at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
            at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
            at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
            at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
            at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:395)
            at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:144)
            at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:887)
            at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:759)
            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:480)
            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:416)
            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:163)
            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:223)
            at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderFields(DelegatingHttpsURLConnection.java:178)
            at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderFields(HttpsURLConnectionImpl.java:26)
            at com.github.kittinunf.fuel.toolbox.HttpClient.retrieveResponse(HttpClient.kt:131)
            at com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:75)
            at com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:38)
            at com.github.kittinunf.fuel.core.requests.RequestTask.executeRequest(RequestTask.kt:23)
            at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:44)
            at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
            at com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:28)
            at com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:20)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
            at java.lang.Thread.run(Thread.java:764)```

**Comment by iNoles** [comment]
Caused by: java.net.SocketTimeoutException: timeout and Caused by: java.net.SocketException: socket is closed

maybe you should increase timeouts?

**Comment by ChrissinjinTurner** [comment]
I have tried to do that by using the `https://httpbin.org/delay/5` to test and see if that could solve it. Without being able to reproduce it, it's hard to tell if it works. I am just not sure that's the issue because the timeouts were actually lower when we were on version 1.15 (they were set to 8 seconds and now they are the defaults which i think is 15).

**Comment by ChrissinjinTurner** [comment]
Some of the other major errors include:
`Caused by: com.github.kittinunf.fuel.core.FuelError: SSL handshake timed out`
`Caused by: com.github.kittinunf.fuel.core.FuelError: Unable to resolve host "url": No address associated with hostname`
`Caused by: com.github.kittinunf.fuel.core.FuelError: Read error: ssl=0x7d6dfb3488: I/O error during system call, Software caused connection abort`

These all started occurring after the version upgrade. I assume they are all related to one issue, I am just trying to figure out what that issue is.

**Comment by ChrissinjinTurner** [comment]
So while searching around for what could possibly cause the crash I came across this that seems like it might be the cause. What exactly would be the fix for this?

```
<issue
        id="DuplicatePlatformClasses"
        severity="Fatal"
        message="`json` defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don&apos;t have the same problem (for example, for `httpclient` use `HttpUrlConnection` or `okhttp` instead), or repackaging the library using something like `jarjar`."
        category="Correctness"
        priority="8"
        summary="Duplicate Platform Classes"
        explanation="There are a number of libraries that duplicate not just functionality of the Android platform but using the exact same class names as the ones provided in Android -- for example the apache http classes. This can lead to unexpected crashes.&#xA;&#xA;To solve this, you need to either find a newer version of the library which no longer has this problem, or to repackage the library (and all of its dependencies) using something like the `jarjar` tool, or finally, rewriting the code to use different APIs (for example, for http code, consider using `HttpUrlConnection` or a library like `okhttp`)."
        errorLine1="    implementation &apos;com.github.kittinunf.fuel:fuel-json:2.1.0&apos;"
        errorLine2="                                                   ~~~~">
    </issue>
