### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by BufoMarinus** [kittinunf/fuel#706]
Fatal Exception: java.lang.NoClassDefFoundError: com.github.kittinunf.fuel.core.FuelError
       at com.github.kittinunf.fuel.core.requests.CancellableRequest.join(CancellableRequest.kt:39)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

Caused by java.lang.StackOverflowError: stack size 1041KB
       at com.github.kittinunf.fuel.core.requests.RequestTask.executeRequest(RequestTask.kt:24)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:44)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
       at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:166)
       at com.github.kittinunf.fuel.core.requests.DefaultRequest.response(DefaultRequest.kt:446)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt:60)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(:4)
       at com.github.kittinunf.fuel.core.requests.RequestTask.prepareResponse(RequestTask.kt:31)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:47)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
       at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:166)
       at com.github.kittinunf.fuel.core.requests.DefaultRequest.response(DefaultRequest.kt:446)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt:60)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(:4)
       at com.github.kittinunf.fuel.core.requests.RequestTask.prepareResponse(RequestTask.kt:31)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:47)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
       at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:166)
       at com.github.kittinunf.fuel.core.requests.DefaultRequest.response(DefaultRequest.kt:446)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt:60)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(:4)
       at com.github.kittinunf.fuel.core.requests.RequestTask.prepareResponse(RequestTask.kt:31)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:47)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
       at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:166)
       at com.github.kittinunf.fuel.core.requests.DefaultRequest.response(DefaultRequest.kt:446)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt:60)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(:4)
       at com.github.kittinunf.fuel.core.requests.RequestTask.prepareResponse(RequestTask.kt:31)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:47)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
       at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:166)
       at com.github.kittinunf.fuel.core.requests.DefaultRequest.response(DefaultRequest.kt:446)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt:60)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(:4)
       at com.github.kittinunf.fuel.core.requests.RequestTask.prepareResponse(RequestTask.kt:31)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:47)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
       at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:166)
       at com.github.kittinunf.fuel.core.requests.DefaultRequest.response(DefaultRequest.kt:446)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt:60)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(:4)
       at com.github.kittinunf.fuel.core.requests.RequestTask.prepareResponse(RequestTask.kt:31)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:47)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
       at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:166)
       at com.github.kittinunf.fuel.core.requests.DefaultRequest.response(DefaultRequest.kt:446)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt:60)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(:4)
       at com.github.kittinunf.fuel.core.requests.RequestTask.prepareResponse(RequestTask.kt:31)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:47)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
       at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:166)
       at com.github.kittinunf.fuel.core.requests.DefaultRequest.response(DefaultRequest.kt:446)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt:60)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(:4)
       at com.github.kittinunf.fuel.core.requests.RequestTask.prepareResponse(RequestTask.kt:31)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:47)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
       at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:166)
       at com.github.kittinunf.fuel.core.requests.DefaultRequest.response(DefaultRequest.kt:446)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt:60)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(:4)
       at com.github.kittinunf.fuel.core.requests.RequestTask.prepareResponse(RequestTask.kt:31)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:47)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
       at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:166)
       at com.github.kittinunf.fuel.core.requests.DefaultRequest.response(DefaultRequest.kt:446)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(RedirectionInterceptor.kt:60)
       at com.github.kittinunf.fuel.core.interceptors.RedirectionInterceptorKt$redirectResponseInterceptor$1$1.invoke(:4)
       at com.github.kittinunf.fuel.core.requests.RequestTask.prepareResponse(RequestTask.kt:31)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:47)
       at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
       at com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:28)
       at com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:20)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

**Comment by iNoles** [comment]
Which Fuel Version you uses?

**Comment by kittinunf** [comment]
I think we need more information on this. I will close this for now due to lack of activity
