### ISSUE TITLE
Not pass detectUntaggedSockets()

### ISSUE THREAD

**Issue by imknown** [kittinunf/fuel#707]
# Bug Report

## Description
Not pass `StrictMode.VmPolicy.Builder.detectUntaggedSockets()`

## To Reproduce

``` Kotlin
StrictMode.VmPolicy.Builder().detectUntaggedSockets()

...

url.httpDownload()
   .fileDestination { _, _ -> savedLldJsonFile }
   .awaitByteArrayResult()
   .fold(success, failure)
```

## Expected behavior
No warings/errors.

### Development Machine
 - OS: Windows 10
 - IDE: Android Studio 3.5.3
 - Fuel version: 2.2.1

## Additional context
```
2019-12-21 17:58:43.892 10436-10485/net.imknown.android.forefrontinfo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2019-12-21 17:58:44.375 10436-10485/net.imknown.android.forefrontinfo D/StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2124)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:52)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:372)
        at libcore.io.ForwardingOs.socket(ForwardingOs.java:217)
        at libcore.io.IoBridge.socket(IoBridge.java:658)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:128)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
        at java.net.Socket.createImpl(Socket.java:489)
        at java.net.Socket.getImpl(Socket.java:552)
        at java.net.Socket.setSoTimeout(Socket.java:1180)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
        at com.github.kittinunf.fuel.toolbox.HttpClient.sendRequest(HttpClient.kt:135)
        at com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:78)
        at com.github.kittinunf.fuel.toolbox.HttpClient.access$doRequest(HttpClient.kt:28)
        at com.github.kittinunf.fuel.toolbox.HttpClient.awaitRequest(HttpClient.kt:66)
        at com.github.kittinunf.fuel.core.requests.SuspendableRequest.executeRequest(SuspendableRequest.kt:21)
        at com.github.kittinunf.fuel.core.requests.SuspendableRequest.awaitResult(SuspendableRequest.kt:40)
        at com.github.kittinunf.fuel.core.DeserializableKt.awaitResult(Deserializable.kt:240)
        at net.imknown.android.forefrontinfo.GatewayApi$Companion$downloadLldJsonFile$$inlined$awaitByteArrayResult$1.invokeSuspend(Coroutines.kt:43)
        at net.imknown.android.forefrontinfo.GatewayApi$Companion$downloadLldJsonFile$$inlined$awaitByteArrayResult$1.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at net.imknown.android.forefrontinfo.GatewayApi$Companion.downloadLldJsonFile(GatewayApi.kt:90)
        at net.imknown.android.forefrontinfo.ui.home.HomeFragment.collectionDataset(HomeFragment.kt:143)
        at net.imknown.android.forefrontinfo.base.BaseListFragment.collectionDatasetCaller(BaseListFragment.kt:115)
        at net.imknown.android.forefrontinfo.base.BaseListFragment.collectionDatasetCaller$default(BaseListFragment.kt:110)
        at net.imknown.android.forefrontinfo.base.BaseListFragment$onActivityCreated$1.invokeSuspend(BaseListFragment.kt:52)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(C
2019-12-21 17:58:44.421 10436-10485/net.imknown.android.forefrontinfo W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
2019-12-21 17:58:44.421 10436-10485/net.imknown.android.forefrontinfo I/Process: Sending signal. PID: 10436 SIG: 9
```

**Comment by kittinunf** [comment]
Hmm, what should we do from our side to get rid of this violation? 🤔💭
