### ISSUE TITLE
Crash android.os.NetworkOnMainThreadException

### ISSUE THREAD

**Issue by outsbook** [kittinunf/fuel#740]
# Bug Report
```
Fatal Exception: android.os.NetworkOnMainThreadException
       at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
       at java.net.SocketInputStream.read(SocketInputStream.java:175)
       at java.net.SocketInputStream.read(SocketInputStream.java:144)
       at com.android.okhttp.okio.Okio$2.read(Okio.java:145)
       at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:61)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:595)
       at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:397)
       at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
       at java.io.FilterInputStream.read(FilterInputStream.java:133)
       at com.github.kittinunf.fuel.util.ProgressInputStream.read(ProgressInputStream.kt:46)
       at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
       at java.io.FilterInputStream.read(FilterInputStream.java:107)
       at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:110)
       at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
       at com.github.kittinunf.fuel.core.requests.DefaultBody.writeTo(DefaultBody.kt:87)
       at com.github.kittinunf.fuel.core.requests.DefaultBody.toByteArray(DefaultBody.kt:50)
       at com.github.kittinunf.fuel.core.Response.getData(Response.kt:32)
       at com.longviewlabs.egged.repositories.FriendRepository$addContactFriend$1.invoke(FriendRepository.kt:46)
       at com.longviewlabs.egged.repositories.FriendRepository$addContactFriend$1.invoke(FriendRepository.kt:15)
       at com.github.kittinunf.fuel.core.DeserializableKt$response$2.invoke(Deserializable.kt:106)
       at com.github.kittinunf.fuel.core.DeserializableKt$response$2.invoke(:6)
       at com.github.kittinunf.fuel.core.DeserializableKt$response$asyncRequest$2$1.invoke(Deserializable.kt:201)
       at com.github.kittinunf.fuel.core.DeserializableKt$response$asyncRequest$2$1.invoke()
       at com.github.kittinunf.fuel.core.RequestExecutionOptionsKt$sam$java_lang_Runnable$0.run(:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7811)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
```

**Comment by kittinunf** [comment]
Usually, you should not make network request on main thread. I don't think this is the library bug. 

Could you try the async option that provides by the library? For example, `callback`, `RxJava` or `coroutine` support.
