### ISSUE TITLE
Response's toString() method causes `NetworkOnMainThreadException` upon falling request

### ISSUE THREAD

**Issue by wenhaowu-finnair** [kittinunf/fuel#742]
# Bug Report

## Description
In Android, when logging the response object upon failing request, a fatal exception `NetworkOnMainThreadException` is throw and causing the app to crash.

## To Reproduce
```Kotlin
"https://httpbin.org/get1" //404
    .httpGet()
    .responseString() { _, response, _ ->
        Log.e("ABC", response.toString())
    }
```

## Expected behavior
Would be nice to print the actual http error 

### Development Machine

 - IDE: Android Studio
 - Fuel version: 2.2.2
 - Kotlin version: 1.3.72

## Stack trace for crash
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 1531
    android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
        at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:424)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:564)
        at com.android.okhttp.okio.Okio$2.read(Okio.java:145)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:61)
        at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:602)
        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:397)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.github.kittinunf.fuel.util.ProgressInputStream.read(ProgressInputStream.kt:46)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:106)
        at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
        at com.github.kittinunf.fuel.core.requests.DefaultBody.writeTo(DefaultBody.kt:87)
        at com.github.kittinunf.fuel.core.requests.DefaultBody.toByteArray(DefaultBody.kt:50)
        at com.github.kittinunf.fuel.core.BodyRepresentationKt.representationOfBytes(BodyRepresentation.kt:25)
        at com.github.kittinunf.fuel.core.requests.DefaultBody.asString(DefaultBody.kt:30)
        at com.github.kittinunf.fuel.core.Response.toString(Response.kt:50)
        at com.example.myapplication.MainActivity$onCreate$1.invoke(MainActivity.kt:18)
        at com.example.myapplication.MainActivity$onCreate$1.invoke(MainActivity.kt:9)
```

**Comment by iNoles** [comment]
Android does prevent network on the main thread by default. you wouldn't get actual http error if you tried to run it on main thread.

**Comment by wenhaowu-finnair** [comment]
> Android does prevent network on the main thread by default. you wouldn't get actual http error if you tried to run it on main thread.

Hi thanks for replying. I do understand that request needs to be made in worker-thread. But in my example, I use Fuel's callback mechanism. If I understand correctly from READEME, it should already switch thread for making the request. For reference the below example works without throwing `NetworkOnMainThread` exception:
```Kotin
"https://httpbin.org/get" //200
    .httpGet()
    .responseString { _, response, _ ->
        Log.e("ABC", response.toString())
    }
```
So the only problem is when the request failed (400/401/404...), calling response's toString() method mysterically causes the exception.

**Comment by kittinunf** [comment]
@wenhaowu-finnair I tried the following code and it works perfectly (with error of 401 NOT_FOUND ofc)

```kotlin
"https://httpbin.org/get1"
            .httpGet()
            .responseString { request, response, result ->
                println(request.toString())
                println(result.toString())
            }
```

Result

```
2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: --> GET https://httpbin.org/get1?key=value
2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: Body : (empty)
2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: Headers : (1)
2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: Device : Android
2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: [Failure: HTTP Exception 404 NOT FOUND
2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: 	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:84)
2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: 	com.github.kittinunf.fuel.core.FuelError$Companion.wrap$default(FuelError.kt:83)
2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: 	com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:30)
2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: 	com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:20)
2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: 	java.util.concurrent.FutureTask.run(FutureTask.java:266)

```

Can you check whether there is something wrong on your side?

**Comment by wenhaowu-finnair** [comment]
> @wenhaowu-finnair I tried the following code and it works perfectly (with error of 401 NOT_FOUND ofc)
> 
> ```kotlin
> "https://httpbin.org/get1"
>             .httpGet()
>             .responseString { request, response, result ->
>                 println(request.toString())
>                 println(result.toString())
>             }
> ```
> 
> Result
> 
> ```
> 2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: --> GET https://httpbin.org/get1?key=value
> 2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: Body : (empty)
> 2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: Headers : (1)
> 2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: Device : Android
> 2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: [Failure: HTTP Exception 404 NOT FOUND
> 2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: 	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:84)
> 2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: 	com.github.kittinunf.fuel.core.FuelError$Companion.wrap$default(FuelError.kt:83)
> 2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: 	com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:30)
> 2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: 	com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:20)
> 2020-05-15 13:15:15.861 18476-18476/com.example.fuel I/System.out: 	java.util.concurrent.FutureTask.run(FutureTask.java:266)
> ```
> 
> Can you check whether there is something wrong on your side?

Hi thinks for replying. The problem is with **response**'s toString method, not request nor result. Could you try with that?

**Comment by kittinunf** [comment]
Ahh, I missed that ... 

Yeah with the `response.toString()`, it basically read/touch the `InputStream` for a response once again. 

In the callback, we switch back automatically to the main thread in the case of Android. So it is kinda similar to touching the network on the main thread. So, the NetworkOnMainThread exception is thrown.

I think it should crash regardless whether it is success or failure though >_<

**Comment by wenhaowu-finnair** [comment]
@kittinunf Good to know. Can you elaborate more about this:

> Yeah with the `response.toString()`, it basically read/touch the `InputStream` for a response once again.

So if I understand it correctly, does it mean the actual request would be sent again when we call `toString()`?

**Comment by geofferyj** [comment]
@kittinunf this has not been fixed

any work around?

**Comment by japanconman** [comment]
> @kittinunf this has not been fixed
> 
> any work around?

i tried using FuelManager with ResponseInterceptor (mentioned in #756 ] seems able to go around the NetworkOnMainThreadException issue.

val manager = FuelManager()
manager.addResponseInterceptor(LogResponseInterceptor)
manager.request(....)
