### ISSUE TITLE
Connection Refused: Fatal Exception

### ISSUE THREAD

**Issue by tony23** [kittinunf/fuel#786]
My apologies if this is inappropriate to post here; I am new to Kotlin and I think that may be a big part of my problem, but I have not been able to find a solution. I have asked on a Kotlin forum but so far no response, I'm hoping someone can help me or at least point me the right way.

I have a very simple usage where I am trying to get a simple string value back from a HTTP endpoint:
```
try {
    Fuel.get(url, params).responseString { request, response, result ->
        handleResults(result.get())
    }
}
catch (e:Exception) {
    handleError(e)
}
```
But when there is a connection problem such as the server being down, I get a fatal exception that isn't handled by my catch block. This action happens when the app opens, so this is causing the app to fail completely, crashing immediately upon start. I just want to get past this so I can display an error for the user.

I have been reading about coroutines and async operations to try to find a way around this, but I haven't found anything that works with the code I'm using. I'm hoping someone can help me understand how to handle this error better?

This might be a bug, but I think it's more likely just my inexperience with Kotlin. For reference, here is the full stack trace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.my.app PID: 19026
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
     Caused by: Connection refused
    com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:84)
    com.github.kittinunf.fuel.core.FuelError$Companion.wrap$default(FuelError.kt:83)
    com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:30)
    com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:20)
    java.util.concurrent.FutureTask.run(FutureTask.java:237)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    java.lang.Thread.run(Thread.java:761)
    Caused by: Connection refused
    com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
    com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:40)
    Caused by: java.net.ConnectException: Connection refused
    java.net.PlainSocketImpl.socketConnect(Native Method)
    java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
    java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
    java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
    java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
    java.net.Socket.connect(Socket.java:586)
    com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
    com.android.okhttp.Connection.connectSocket(Connection.java:196)
    com.android.okhttp.Connection.connect(Connection.java:172)
    com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
    com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
    com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
    com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
    com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
    com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
    com.github.kittinunf.fuel.toolbox.HttpClient.sendRequest(HttpClient.kt:145)
    com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:79)
    com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:37)
    com.github.kittinunf.fuel.core.requests.RequestTask.executeRequest(RequestTask.kt:23)
    com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:44)
    com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
    com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:28)
    com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:20)
    java.util.concurrent.FutureTask.run(FutureTask.java:237)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    java.lang.Thread.run(Thread.java:761)
      
        at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:84)
        at com.github.kittinunf.fuel.core.FuelError$Companion.wrap$default(FuelError.kt:83)
        at com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:30)
        at com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:20)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: Connection refused
    com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
    com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:40)
    Caused by: java.net.ConnectException: Connection refused
    java.net.PlainSocketImpl.socketConnect(Native Method)
    java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
    java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
    java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
    java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
    java.net.Socket.connect(Socket.java:586)
    com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
    com.android.okhttp.Connection.connectSocket(Connection.java:196)
    com.android.okhttp.Connection.connect(Connection.java:172)
    com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
    com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
    com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
    com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
    com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
    com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
    com.github.kittinunf.fuel.toolbox.HttpClient.sendRequest(HttpClient.kt:145)
    com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:79)
    com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:37)
    com.github.kittinunf.fuel.core.requests.RequestTask.executeRequest(RequestTask.kt:23)
    com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:44)
    com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
    com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:28)
    com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:20)
    java.util.concurrent.FutureTask.run(FutureTask.java:237)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    java.lang.Thread.run(Thread.java:761)
   
        at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
        at com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:40)
     Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
        at java.net.Socket.connect(Socket.java:586)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
        at com.android.okhttp.Connection.connectSocket(Connection.java:196)
        at com.android.okhttp.Connection.connect(Connection.java:172)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
        at com.github.kittinunf.fuel.toolbox.HttpClient.sendRequest(HttpClient.kt:145)
        at com.github.kittinunf.fuel.toolbox.HttpClient.doRequest(HttpClient.kt:79)
        at com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:37)
        at com.github.kittinunf.fuel.core.requests.RequestTask.executeRequest(RequestTask.kt:23)
        at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:44)
        at com.github.kittinunf.fuel.core.requests.RequestTask.call(RequestTask.kt:14)
        at com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:28)
        at com.github.kittinunf.fuel.core.requests.RequestTaskCallbacks.call(RequestTaskCallbacks.kt:20)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by kittinunf** [comment]
I don't think you should use get() if you don't expect it to be thrown. `result.get()` will throw the underlying exception inside. 

The better way for you is to handle it nicely for example with `result.failure`. Consider the following;


```

**Comment by tony23** [comment]
I'm afraid I don't quite understand.

I expect things to work normally most of the time, but there are cases (such as the device is not connected to a network) where it fails, and the exception crashes the app.

I don't want to consume the failure result. If it fails, then there is nothing to do. I want to consume the successful result, but not get a fatal error when something goes wrong.

**Comment by kittinunf** [comment]
You are absolutely right that you should expect things to work normally and most of the time it should work. It is a valid assumption. 

However, things may go wrong and error will eventually appear, users' phones might go off the grid, or as you mentioned the server may be down.

As I mentioned, I personally believe that you should have the error case without do the explicit catch. [Result](https://github.com/kittinunf/Result) is designed to handle the error without explicit catch the exception, we have a couple of handy methods to handle when you face error.

Result's `get()` would throw the exception, if you don't want this you should probably want to handle it differently. At the very least, doing `if` check is probably sufficient if you don't care the failure case.

```
val result = ....

if (result is Result.Success) {
  //do something the value.
}
```
